### ISSUE TITLE
Create a better WeightInitializer class to easily initialize weights of a model

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/models#14]
I think we should be more Object Oriented than what we already have i.e. only one `WeightInitializer` class with multiple types of initialization method. There is probably a design pattern to that the right way.

**Comment by MarcCote** [comment]
According to Issue #13, we should put the `WeightInitializer` class in the _smart-learner_ library.

**Comment by ASalvail** [comment]
Will do something, probably before the end of the day. Will deprecate the initializer in _smart-models_.

**Comment by ASalvail** [comment]
See PR #17 and PR #24 from smartpy.
